[[profiles.apps]]
start_virtual_compositor = true
title = 'Wolf UI Docker'

    [profiles.apps.runner]
    base_create_json = '''{
      "HostConfig": {
        "IpcMode": "host",
        "CapAdd": ["NET_RAW", "MKNOD", "NET_ADMIN", "SYS_ADMIN", "SYS_NICE"],
        "Privileged": false,
        "DeviceCgroupRules": ["c 13:* rmw", "c 244:* rmw"]
      }
    }'''
    devices = []
    env = [ 'GOW_REQUIRED_DEVICES=/dev/input/event* /dev/dri/* /dev/nvidia*', 'WOLF_SOCKET_PATH=/var/run/wolf/wolf.sock' ]
    image = 'ghcr.io/games-on-whales/wolf-ui:main'
    mounts = ['/var/run/docker.sock:/var/run/docker.sock', '/var/run/wolf/wolf.sock:/var/run/wolf/wolf.sock', '/etc/wolf:/etc/wolf']
    name = 'WolfPegasus'
    ports = []
    type = 'docker'